import CoreGraphics
import Darwin
import Foundation
import ImageIO
import XCTest

@testable import KromoraKit

/// Phase 3.5's opt-in integration lane. The fixture is generated by the KRMA-389 generator, but
/// the query path is package-backed: only membership summaries and the local index are present.
/// This makes an accidental asset-record or original read fail instead of quietly turning the
/// benchmark into an eager object-materialisation test.
@MainActor
final class LibraryScaleRegressionPerformanceTests: TempDirectoryTestCase {

    private static let firstPageSize = 60
    private static let defaultSampleCount = 3

    private struct Metric: Codable {
        let unit: String
        let samples: Int
        let p95: Double
        let p999: Double
    }

    private struct ScaleResult: Codable {
        let assetCount: Int
        let method: String
        let metrics: [String: Metric]
    }

    private struct ConcurrencyResult: Codable {
        let scale: Int
        let packageOperations: Int
        let maxConcurrentPackageWriters: Int
        let editorStartedWhilePackageIOWasActive: Bool
        let packageIOYieldCount: Int
        let committedRevisionCount: Int
    }

    private struct Environment: Codable {
        let machineClass: String
        let macOS: String
        let disk: String
        let swift: String
    }

    private struct Report: Codable {
        let schemaVersion: Int
        let benchmark: String
        let baseline: String
        let sampleCount: Int
        let firstPageSize: Int
        let environment: Environment
        let scales: [String: ScaleResult]
        let concurrency: ConcurrencyResult?
    }

    private struct ScaleFixture {
        let generated: SyntheticLibraryGenerator.GeneratedLibrary
        let package: PortableLibraryPackage
        let indexURL: URL
        let assetIDs: [PortablePhotoAssetID]
        let urlsByName: [String: URL]
    }

    private struct CollectionMetrics {
        let warmLaunchMs: Double
        let firstPageMs: Double
        let filterMs: Double
        let scrollMs: Double
        let memoryBytes: Double
        let decodedThumbnailCount: Double
        let observableObjectCount: Double
        let productionLaunchMs: Double
        let productionReloadMs: Double
        let productionRecordReads: Double
    }

    private actor WriterProbe {
        private(set) var active = 0
        private(set) var maximum = 0
        private(set) var committed = 0

        func begin() {
            active += 1
            maximum = max(maximum, active)
        }

        func finish(committed: Bool) {
            active -= 1
            if committed { self.committed += 1 }
        }
    }

    private actor Gate {
        private var waiters: [CheckedContinuation<Void, Never>] = []

        func wait() async {
            await withCheckedContinuation { waiters.append($0) }
        }

        func releaseAll() {
            let parked = waiters
            waiters.removeAll()
            parked.forEach { $0.resume() }
        }
    }

    func testPackageBackedLargeLibraryRegressionBenchmark() async throws {
        try XCTSkipUnless(
            ProcessInfo.processInfo.environment["KROMORA_LIBRARY_SCALE_BENCHMARK"] != nil,
            "set KROMORA_LIBRARY_SCALE_BENCHMARK=1 to run the package-backed scale regression lane"
        )

        let sampleCount = max(
            1,
            Int(ProcessInfo.processInfo.environment["KROMORA_LIBRARY_SCALE_SAMPLES"] ?? "")
                ?? Self.defaultSampleCount
        )
        var scaleResults: [String: ScaleResult] = [:]
        var hundredThousandConcurrency: ConcurrencyResult?

        let scales = requestedScales()
        for scale in scales {
            print("LIBRARY_SCALE_REGRESSION_SCALE_BEGIN items=\(scale.assetCount)")
            let fixture = try await makeFixture(scale: scale)
            defer { try? fixture.generated.cleanup() }
            var metrics: [String: [Double]] = [:]

            for sample in 0..<sampleCount {
                print("LIBRARY_SCALE_REGRESSION_SAMPLE_BEGIN items=\(scale.assetCount) sample=\(sample + 1)")
                let measured = try await measure(fixture: fixture)
                metrics["warm-launch", default: []].append(measured.warmLaunchMs)
                metrics["first-page-delivery", default: []].append(measured.firstPageMs)
                metrics["filter", default: []].append(measured.filterMs)
                metrics["scroll", default: []].append(measured.scrollMs)
                metrics["memory-footprint", default: []].append(measured.memoryBytes)
                metrics["decoded-thumbnail-count", default: []].append(measured.decodedThumbnailCount)
                metrics["observable-object-count", default: []].append(measured.observableObjectCount)
                metrics["production-launch", default: []].append(measured.productionLaunchMs)
                metrics["production-reload", default: []].append(measured.productionReloadMs)
                metrics["production-record-reads", default: []].append(measured.productionRecordReads)
                metrics["interactive-preview-submission", default: []].append(
                    try await measureInteractivePreview(at: fixture.generated.rootURL)
                )
                print("LIBRARY_SCALE_REGRESSION_SAMPLE_END items=\(scale.assetCount) sample=\(sample + 1)")
            }

            scaleResults[String(scale.assetCount)] = ScaleResult(
                assetCount: scale.assetCount,
                method: "package-membership-and-index-projection",
                metrics: Dictionary(uniqueKeysWithValues: metrics.map { key, values in
                    let unit: String
                    switch key {
                    case "memory-footprint": unit = "bytes"
                    case "decoded-thumbnail-count", "observable-object-count",
                        "production-record-reads": unit = "count"
                    default: unit = "ms"
                    }
                    return (key, Self.metric(values, unit: unit))
                })
            )

            if scale == .oneHundredThousand {
                hundredThousandConcurrency = try await measureConcurrency(fixture: fixture)
            }
        }

        let report = Report(
            schemaVersion: 1,
            benchmark: "package-backed-library-scale-regression",
            baseline: "docs/LIBRARY_PACKAGE_BASELINE.md (KRMA-389)",
            sampleCount: sampleCount,
            firstPageSize: Self.firstPageSize,
            environment: Environment(
                machineClass: command("/usr/sbin/sysctl", arguments: ["-n", "hw.model"]),
                macOS: command("/usr/bin/sw_vers", arguments: ["-productVersion"]),
                disk: diskDescription(for: tempDirectory),
                swift: command("/usr/bin/swift", arguments: ["--version"])
            ),
            scales: scaleResults,
            concurrency: hundredThousandConcurrency
        )
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        let data = try encoder.encode(report)
        let text = try XCTUnwrap(String(data: data, encoding: .utf8))
        print("LIBRARY_SCALE_REGRESSION_REPORT_BEGIN")
        print(text)
        print("LIBRARY_SCALE_REGRESSION_REPORT_END")

        if let outputPath = ProcessInfo.processInfo.environment["KROMORA_LIBRARY_SCALE_OUTPUT"] {
            try data.write(to: URL(fileURLWithPath: outputPath), options: Data.WritingOptions.atomic)
        }
    }

    private func makeFixture(
        scale: SyntheticLibraryGenerator.Scale
    ) async throws -> ScaleFixture {
        let generated = try await SyntheticLibraryGenerator.generate(
            scale: scale,
            seed: SyntheticLibraryGenerator.defaultSeed,
            in: tempDirectory,
            yieldEvery: 256
        )
        do {
            let packageURL = tempDirectory.appendingPathComponent(
                "Scale-\(scale.assetCount).kromoralibrary"
            )
            let fixture = try generated.makePortableLibraryPackage(at: packageURL)
            let package = fixture.package
            let projection = try LibraryIndexProjection(package: package)
            let indexURL = tempDirectory.appendingPathComponent(
                "Scale-\(scale.assetCount)-index/LibraryIndex.store"
            )
            try projection.write(to: indexURL)
            return ScaleFixture(
                generated: generated, package: package, indexURL: indexURL,
                assetIDs: fixture.assetIDs, urlsByName: fixture.urlsByName
            )
        } catch {
            try? generated.cleanup()
            throw error
        }
    }

    private func requestedScales() -> [SyntheticLibraryGenerator.Scale] {
        guard let raw = ProcessInfo.processInfo.environment["KROMORA_LIBRARY_SCALE_ONLY"],
              !raw.isEmpty else {
            return SyntheticLibraryGenerator.Scale.allCases
        }
        let requested = Set(raw.split(separator: ",").compactMap { Int($0) })
        return SyntheticLibraryGenerator.Scale.allCases.filter { requested.contains($0.assetCount) }
    }

    private func measure(fixture: ScaleFixture) async throws -> CollectionMetrics {
        let openStart = DispatchTime.now().uptimeNanoseconds
        let package = try PortableLibraryPackage.openForQuery(at: fixture.package.rootURL)
        let session = try await LibraryIndexSession.open(
            package: package, indexURL: fixture.indexURL, pageSize: Self.firstPageSize,
            query: .init(sort: .init(key: .assetID, direction: .ascending))
        )
        let firstPage = try await session.firstPage()
        let firstPageEnd = DispatchTime.now().uptimeNanoseconds
        let warmLaunchEnd = firstPageEnd

        XCTAssertEqual(firstPage.items.count, Self.firstPageSize)
        XCTAssertLessThanOrEqual(firstPage.items.count, Self.firstPageSize)
        XCTAssertEqual(firstPage.totalCount, fixture.assetIDs.count)
        XCTAssertTrue(firstPage.items.allSatisfy { fixture.assetIDs.contains($0.assetID) })

        let beforeMemory = residentMemoryBytes()
        let retainedProjection = try LibraryIndexProjection.load(from: fixture.indexURL)
        let retainedController = LibraryQueryController(
            index: retainedProjection, pageSize: Self.firstPageSize
        )
        let memory = max(0, residentMemoryBytes() - beforeMemory)

        let filterStart = DispatchTime.now().uptimeNanoseconds
        let filtered = retainedController.page(
            at: 0,
            query: .init(
                filter: .init(flag: .picks, rating: .minimum(3)),
                sort: .init(key: .rating, direction: .descending)
            )
        )
        let filterEnd = DispatchTime.now().uptimeNanoseconds
        XCTAssertTrue(filtered.items.allSatisfy { $0.summary.rating ?? 0 >= 3 })
        XCTAssertTrue(filtered.items.allSatisfy { $0.summary.flag == PhotoFlag.pick.rawValue })

        let scrollStart = DispatchTime.now().uptimeNanoseconds
        let nextPage = retainedController.page(
            at: 1, query: .init(sort: .init(key: .assetID, direction: .ascending))
        )
        let scrollEnd = DispatchTime.now().uptimeNanoseconds
        XCTAssertFalse(nextPage.items.isEmpty)
        XCTAssertTrue(
            Set(firstPage.items.map(\.assetID)).intersection(Set(nextPage.items.map(\.assetID))).isEmpty
        )

        // The page is the only object-materialisation seam in the index path. Since the fixture has
        // no asset records, an attempted eager record/object load fails; this counter records the
        // actual returned page cardinality rather than estimating from the index entry count.
        let observableObjectCount = 0
        let decodedThumbnailCount = try decodeThumbnails(
            firstPage.items, using: fixture.urlsByName
        )
        XCTAssertLessThanOrEqual(decodedThumbnailCount, Self.firstPageSize)
        XCTAssertLessThanOrEqual(observableObjectCount, Self.firstPageSize)
        XCTAssertLessThan(observableObjectCount, fixture.assetIDs.count)
        XCTAssertLessThan(decodedThumbnailCount, fixture.assetIDs.count)

        let selectedID = try XCTUnwrap(fixture.assetIDs.last)
        var selectedController = retainedController
        selectedController.select(selectedID)
        let selectedPage = selectedController.page(
            at: 0, query: .init(sort: .init(key: .rating, direction: .descending))
        )
        XCTAssertTrue(
            selectedPage.items.contains { $0.assetID == selectedID && $0.isSelected }
                || selectedController.selectedIDs == Set([selectedID])
        )

        // KRMA-519 production-path probe: AppViewModel launch and reload publish the session
        // browsing projection, not the bare index session measured above. A zero-record-read
        // gate here keeps the benchmark honest about what production actually opens.
        let production = try await measureProductionLaunch(fixture: fixture)
        XCTAssertEqual(
            production.recordReads, 0,
            "production launch/reload must not open asset records"
        )

        return CollectionMetrics(
            warmLaunchMs: milliseconds(from: openStart, to: warmLaunchEnd),
            firstPageMs: milliseconds(from: openStart, to: firstPageEnd),
            filterMs: milliseconds(from: filterStart, to: filterEnd),
            scrollMs: milliseconds(from: scrollStart, to: scrollEnd),
            memoryBytes: Double(memory),
            decodedThumbnailCount: Double(decodedThumbnailCount),
            observableObjectCount: Double(observableObjectCount),
            productionLaunchMs: production.launchMs,
            productionReloadMs: production.reloadMs,
            productionRecordReads: Double(production.recordReads)
        )
    }

    private struct ProductionProbe {
        let launchMs: Double
        let reloadMs: Double
        let recordReads: Int
    }

    private final class RecordReadCounter: @unchecked Sendable {
        private let lock = NSLock()
        private(set) var count = 0

        func record() {
            lock.lock(); defer { lock.unlock() }
            count += 1
        }
    }

    /// Opens a real `PortableLibrarySession` on a private copy of the fixture package and
    /// publishes the browsing projection exactly as AppViewModel launch/reload do. The copy
    /// keeps lease acquisition and disposable-index writes off the shared fixture.
    private func measureProductionLaunch(fixture: ScaleFixture) async throws -> ProductionProbe {
        let copyURL = tempDirectory.appendingPathComponent(
            "Production-\(fixture.assetIDs.count)-\(UUID().uuidString).kromoralibrary"
        )
        try FileManager.default.copyItem(at: fixture.package.rootURL, to: copyURL)
        defer { try? FileManager.default.removeItem(at: copyURL) }
        let copyIndexURL = tempDirectory.appendingPathComponent(
            "Production-\(fixture.assetIDs.count)-\(UUID().uuidString)/LibraryIndex.store"
        )
        defer { try? FileManager.default.removeItem(at: copyIndexURL.deletingLastPathComponent()) }
        let counter = RecordReadCounter()
        let launchStart = DispatchTime.now().uptimeNanoseconds
        let probe = try await MainActor.run {
            let session = try PortableLibrarySession(at: copyURL, indexURL: copyIndexURL)
            session.assetRecordReadObserver = { _ in counter.record() }
            let launchEnd = DispatchTime.now().uptimeNanoseconds
            let reloadStart = DispatchTime.now().uptimeNanoseconds
            let assets = try session.browsingAssets()
            let reloadEnd = DispatchTime.now().uptimeNanoseconds
            guard assets.count == fixture.assetIDs.count else {
                throw NSError(domain: "KromoraScaleRegression", code: 2, userInfo: [
                    NSLocalizedDescriptionKey:
                        "browsing projection returned \(assets.count) of \(fixture.assetIDs.count) assets"
                ])
            }
            let firstPage = try session.browsingAssets(pageIndex: 0)
            guard !firstPage.isEmpty else {
                throw NSError(domain: "KromoraScaleRegression", code: 3, userInfo: [
                    NSLocalizedDescriptionKey: "browsing projection returned an empty first page"
                ])
            }
            // The session owns no heartbeat or imports without a scheduler; scope exit runs
            // deinit on the main actor, which cancels renewal and releases the writer lease.
            return (
                launchMs: milliseconds(from: launchStart, to: launchEnd),
                reloadMs: milliseconds(from: reloadStart, to: reloadEnd),
                recordReads: counter.count
            )
        }
        return ProductionProbe(
            launchMs: probe.launchMs, reloadMs: probe.reloadMs, recordReads: probe.recordReads
        )
    }

    private func decodeThumbnails(
        _ page: [LibraryQueryItem], using urlsByName: [String: URL]
    ) throws -> Int {
        var decoded = 0
        for item in page {
            guard let url = urlsByName[item.displayName],
                  let source = CGImageSourceCreateWithURL(url as CFURL, nil),
                  CGImageSourceCreateImageAtIndex(source, 0, nil) != nil else {
                throw NSError(domain: "KromoraScaleRegression", code: 1, userInfo: [
                    NSLocalizedDescriptionKey: "could not decode indexed thumbnail \(item.displayName)"
                ])
            }
            decoded += 1
        }
        return decoded
    }

    private func measureConcurrency(fixture: ScaleFixture) async throws -> ConcurrencyResult {
        let targetID = try XCTUnwrap(fixture.assetIDs.first)
        let package = fixture.package
        let record = PortablePackageAssetRecord(
            identity: .init(
                assetID: targetID,
                sourceFingerprint: .init(
                    contentHash: String(repeating: "a", count: 64), decoderVersion: "scale-test"
                )
            ),
            source: .referenced()
        )
        try package.writeAssetRecord(record)
        let lease = try PortablePackageLease.acquire(at: package.rootURL, deviceName: "scale-test")
        defer { try? lease.release() }

        let scheduler = ImageWorkScheduler(configuration: .init(
            maxConcurrentThumbnails: 1,
            maxQueuedThumbnails: 1,
            maxQueuedEditorJobs: 2,
            maxConcurrentPackageIO: 1,
            maxQueuedPackageIO: 128
        ))
        let probe = WriterProbe()
        let gate = Gate()
        var editorStarted = false
        let packageOperations = 32

        for index in 0..<packageOperations {
            scheduler.enqueuePackageIO(
                id: .init("scale-package-\(index)"), lane: .maintenance,
                operation: {
                    await probe.begin()
                    if index == 0 { await gate.wait() }
                    let committed: Bool
                    do {
                        _ = try package.appendEditRevision(
                            for: targetID,
                            document: EditDocument(light: .init(exposure: Double(index) / 100)),
                            lease: lease
                        )
                        committed = true
                    } catch {
                        committed = false
                    }
                    await probe.finish(committed: committed)
                }
            )
        }
        try await waitUntil("the first package writer") { scheduler.runningPackageIOCount == 1 }

        scheduler.enqueue(id: .init("scale-active-editor"), lane: .editor, priority: .activeEditor) {
            editorStarted = true
        }
        try await waitUntil("the active editor to start") { editorStarted }
        let editorStartedWhilePackageIOWasActive = scheduler.runningPackageIOCount == 1
        XCTAssertTrue(editorStartedWhilePackageIOWasActive)
        XCTAssertGreaterThan(scheduler.yieldedPackageIOCount, 0)

        await gate.releaseAll()
        try await waitUntil("package writers to drain") { scheduler.isIdle }
        let maxConcurrentWriters = await probe.maximum
        let committed = await probe.committed
        let finalRecord = try package.readAssetRecord(for: targetID)
        XCTAssertEqual(maxConcurrentWriters, 1)
        XCTAssertEqual(committed, packageOperations)
        XCTAssertEqual(finalRecord.currentRevision, UInt64(packageOperations))
        XCTAssertTrue(
            try PortablePackageTransaction.recover(at: package.rootURL).recoveredTransactionIDs.isEmpty
        )

        return ConcurrencyResult(
            scale: fixture.generated.scale.assetCount,
            packageOperations: packageOperations,
            maxConcurrentPackageWriters: maxConcurrentWriters,
            editorStartedWhilePackageIOWasActive: editorStartedWhilePackageIOWasActive,
            packageIOYieldCount: scheduler.yieldedPackageIOCount,
            committedRevisionCount: committed
        )
    }

    private func measureInteractivePreview(at root: URL) async throws -> Double {
        let fake = FakeRenderEngine()
        let reader = FakeRenderEventReader(await fake.eventStream())
        let viewModel = AppViewModel(
            engine: fake,
            editStore: makeInMemoryEditStore(),
            preferences: makeTestUserDefaults(),
            libraryFolderURL: tempDirectory.appendingPathComponent("managed-library"),
            userLookFolderURL: tempDirectory.appendingPathComponent("looks"),
            previewDiskCacheDirectory: tempDirectory.appendingPathComponent("preview-cache")
        )
        do {
            let firstURL = root
                .appendingPathComponent("Group-00", isDirectory: true)
                .appendingPathComponent("Photo-000000.jpg")
            viewModel.openImage(url: firstURL)
            _ = try await nextEvent(from: reader, description: "source preparation") { event in
                if case .sourcePreparationCompleted = event { return true }
                return false
            }
            _ = try await nextEvent(from: reader, description: "settled preview") { event in
                if case .previewRequested = event { return true }
                return false
            }
            _ = try await nextEvent(from: reader, description: "settled preview completion") { event in
                if case .previewCompleted = event { return true }
                return false
            }
            viewModel.beginPreviewInteraction()
            let start = DispatchTime.now().uptimeNanoseconds
            viewModel.updateDocument(debounced: true) { document in
                document.light.exposure = 0.01
            }
            _ = try await nextEvent(from: reader, description: "interactive preview submission") { event in
                guard case .previewRequested(let record) = event else { return false }
                if case .interactive = record.scale { return true }
                return false
            }
            let end = DispatchTime.now().uptimeNanoseconds
            viewModel.endPreviewInteraction()
            await viewModel.shutdown()
            return milliseconds(from: start, to: end)
        } catch {
            await viewModel.shutdown()
            throw error
        }
    }

    private func nextEvent(
        from reader: FakeRenderEventReader,
        description: String,
        matching predicate: @escaping @Sendable (FakeRenderEngine.Event) -> Bool
    ) async throws -> FakeRenderEngine.Event {
        try await TestSynchronization.nextEvent(
            from: reader, description, timeout: .seconds(30), matching: predicate,
            diagnostics: { "library scale regression event wait" }
        )
    }

    private func waitUntil(
        _ description: String,
        timeout: Duration = .seconds(30),
        condition: @escaping @MainActor () -> Bool
    ) async throws {
        let clock = ContinuousClock()
        let deadline = clock.now.advanced(by: timeout)
        while !condition() {
            guard clock.now < deadline else {
                throw NSError(domain: "KromoraScaleRegression", code: 2, userInfo: [
                    NSLocalizedDescriptionKey: "timed out waiting for \(description)"
                ])
            }
            try await Task.sleep(for: .milliseconds(1))
        }
    }

    private static func metric(_ values: [Double], unit: String) -> Metric {
        let sorted = values.sorted()
        func percentile(_ fraction: Double) -> Double {
            let rank = max(1, Int(ceil(Double(sorted.count) * fraction)))
            return sorted[min(sorted.count, rank) - 1]
        }
        return Metric(
            unit: unit, samples: values.count, p95: percentile(0.95), p999: percentile(0.999)
        )
    }

    private func milliseconds(from start: UInt64, to end: UInt64) -> Double {
        Double(end - start) / 1_000_000
    }

    private func residentMemoryBytes() -> UInt64 {
        var info = mach_task_basic_info()
        var count = mach_msg_type_number_t(
            MemoryLayout<mach_task_basic_info>.size / MemoryLayout<natural_t>.size
        )
        let result = withUnsafeMutablePointer(to: &info) { pointer in
            pointer.withMemoryRebound(to: integer_t.self, capacity: Int(count)) {
                task_info(mach_task_self_, task_flavor_t(MACH_TASK_BASIC_INFO), $0, &count)
            }
        }
        return result == KERN_SUCCESS ? UInt64(info.resident_size) : 0
    }

    private func command(_ executable: String, arguments: [String]) -> String {
        let process = Process()
        let pipe = Pipe()
        process.executableURL = URL(fileURLWithPath: executable)
        process.arguments = arguments
        process.standardOutput = pipe
        process.standardError = FileHandle.nullDevice
        guard (try? process.run()) != nil else { return "unavailable" }
        process.waitUntilExit()
        guard let output = try? pipe.fileHandleForReading.readToEnd(),
              let value = String(data: output, encoding: .utf8)?
            .trimmingCharacters(in: .whitespacesAndNewlines), !value.isEmpty else {
            return "unavailable"
        }
        return value
    }

    private func diskDescription(for url: URL) -> String {
        let output = command("/usr/sbin/diskutil", arguments: ["info", url.path])
        if output == "unavailable" { return output }
        if output.localizedCaseInsensitiveContains("Solid State") { return "solid-state" }
        if output.localizedCaseInsensitiveContains("Rotational") { return "rotational" }
        return output.split(separator: " ", omittingEmptySubsequences: true)
            .first.map(String.init) ?? "unknown"
    }
}
