import CoreGraphics
import Foundation
import ImageIO
import SwiftData
import UniformTypeIdentifiers
import XCTest

@testable import LumoKit

/// Builds the same local-only schema used by the edit store without touching the filesystem.
/// Tests that model a relaunch should retain this container and inject it into both stores.
func makeInMemoryEditContainer() -> ModelContainer {
    let schema = Schema([EditRecord.self])
    let configuration = ModelConfiguration(
        "LumoKitTests.EditStore",
        schema: schema,
        isStoredInMemoryOnly: true,
        cloudKitDatabase: .none
    )
    return try! ModelContainer(for: schema, configurations: [configuration])
}

func makeInMemoryEditStore(
    container: ModelContainer = makeInMemoryEditContainer(),
    artificialWriteDelay: Duration = .zero,
    failuresBeforeSuccess: Int = 0,
    writeStartSignal: AsyncStream<Void>.Continuation? = nil
) -> EditDocumentStore {
    EditDocumentStore(
        modelContainer: container,
        artificialWriteDelay: artificialWriteDelay,
        failuresBeforeSuccess: failuresBeforeSuccess,
        writeStartSignal: writeStartSignal
    )
}

/// Test fixtures are **generated**, never checked in: Lumo's inputs are RAWs
/// and LUT files that run to tens of MB, and a repo full of binary fixtures ages
/// badly. Everything here builds its input from scratch in a temp directory.
enum Fixtures {

    // MARK: - Scratch directory

    /// A unique temp directory that the caller is responsible for removing.
    static func makeTempDirectory(_ label: String = "LumoTests") throws -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("\(label)-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    // MARK: - .cube files

    /// Text of an identity cube of the given size, in the standard layout
    /// (R fastest, then G, then B).
    static func identityCubeText(size: Int, title: String = "identity") -> String {
        var lines = [
            "# generated by Lumo tests",
            "TITLE \"\(title)\"",
            "LUT_3D_SIZE \(size)",
        ]
        let denom = Float(size - 1)
        for b in 0..<size {
            for g in 0..<size {
                for r in 0..<size {
                    lines.append(
                        String(
                            format: "%.6f %.6f %.6f",
                            Float(r) / denom, Float(g) / denom, Float(b) / denom
                        ))
                }
            }
        }
        return lines.joined(separator: "\n") + "\n"
    }

    /// Write `text` to `name` inside `directory`, optionally converting the line
    /// endings first (several vendor LUTs in the wild ship CRLF).
    @discardableResult
    static func writeCube(
        _ text: String,
        named name: String,
        in directory: URL,
        lineEnding: String = "\n"
    ) throws -> URL {
        let url = directory.appendingPathComponent(name)
        let converted =
            lineEnding == "\n"
            ? text
            : text.replacingOccurrences(of: "\n", with: lineEnding)
        try converted.write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    // MARK: - Images

    /// A solid-color RGB CGImage.
    static func makeCGImage(
        width: Int, height: Int, red: CGFloat = 0.5,
        green: CGFloat = 0.4, blue: CGFloat = 0.3
    ) throws -> CGImage {
        let space = CGColorSpaceCreateDeviceRGB()
        guard
            let ctx = CGContext(
                data: nil, width: width, height: height,
                bitsPerComponent: 8, bytesPerRow: width * 4, space: space,
                bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
            )
        else { throw FixtureError.cannotCreateContext }
        ctx.setFillColor(red: red, green: green, blue: blue, alpha: 1)
        ctx.fill(CGRect(x: 0, y: 0, width: width, height: height))
        guard let image = ctx.makeImage() else { throw FixtureError.cannotCreateContext }
        return image
    }

    /// Write a JPEG whose **pixel buffer** is `width`×`height` but which carries
    /// `orientation` as its EXIF tag — i.e. exactly what a camera writes when
    /// the body was rotated. Orientation 6 means "rotate 90° CW to display", so
    /// a landscape buffer displays as portrait.
    @discardableResult
    static func writeJPEG(
        width: Int,
        height: Int,
        orientation: Int,
        named name: String,
        in directory: URL
    ) throws -> URL {
        let url = directory.appendingPathComponent(name)
        let image = try makeCGImage(width: width, height: height)
        guard
            let dest = CGImageDestinationCreateWithURL(
                url as CFURL, UTType.jpeg.identifier as CFString, 1, nil
            )
        else { throw FixtureError.cannotCreateDestination }

        let properties: [CFString: Any] = [
            kCGImagePropertyOrientation: orientation,
            kCGImagePropertyTIFFDictionary: [
                kCGImagePropertyTIFFOrientation: orientation
            ] as [CFString: Any],
        ]
        CGImageDestinationAddImage(dest, image, properties as CFDictionary)
        guard CGImageDestinationFinalize(dest) else { throw FixtureError.cannotWriteImage }
        return url
    }

    /// Write the asymmetric gradient used by orientation tests as a JPEG. A flat fixture can prove
    /// that the axes were swapped, but not that a mirror or 180° transform was applied in the right
    /// direction.
    @discardableResult
    static func writeGradientJPEG(
        width: Int,
        height: Int,
        orientation: Int,
        named name: String,
        in directory: URL
    ) throws -> URL {
        try writeOrientedImage(
            makeGradientCGImage(width: width, height: height),
            typeIdentifier: UTType.jpeg.identifier,
            orientation: orientation,
            named: name,
            in: directory
        )
    }

    /// HEIC is optional on the runner (the encoder is provided by the installed ImageIO codecs), so
    /// callers can skip the format-specific assertion when this environment cannot write one.
    static func writeGradientHEIC(
        width: Int,
        height: Int,
        orientation: Int,
        named name: String,
        in directory: URL
    ) throws -> URL? {
        let url = directory.appendingPathComponent(name)
        guard let dest = CGImageDestinationCreateWithURL(
            url as CFURL, UTType.heic.identifier as CFString, 1, nil
        ) else { return nil }
        let properties: [CFString: Any] = [
            kCGImagePropertyOrientation: orientation,
            kCGImagePropertyTIFFDictionary: [
                kCGImagePropertyTIFFOrientation: orientation
            ] as [CFString: Any],
        ]
        CGImageDestinationAddImage(
            dest, try makeGradientCGImage(width: width, height: height), properties as CFDictionary
        )
        guard CGImageDestinationFinalize(dest) else { return nil }
        return url
    }

    private static func writeOrientedImage(
        _ image: CGImage,
        typeIdentifier: String,
        orientation: Int,
        named name: String,
        in directory: URL
    ) throws -> URL {
        let url = directory.appendingPathComponent(name)
        guard let dest = CGImageDestinationCreateWithURL(
            url as CFURL, typeIdentifier as CFString, 1, nil
        ) else { throw FixtureError.cannotCreateDestination }
        let properties: [CFString: Any] = [
            kCGImagePropertyOrientation: orientation,
            kCGImagePropertyTIFFDictionary: [
                kCGImagePropertyTIFFOrientation: orientation
            ] as [CFString: Any],
        ]
        CGImageDestinationAddImage(dest, image, properties as CFDictionary)
        guard CGImageDestinationFinalize(dest) else { throw FixtureError.cannotWriteImage }
        return url
    }

    /// Write a JPEG carrying a set of EXIF/TIFF/GPS values, for metadata tests.
    @discardableResult
    static func writeJPEG(
        named name: String,
        in directory: URL,
        exif: [CFString: Any] = [:],
        tiff: [CFString: Any] = [:],
        gps: [CFString: Any] = [:]
    ) throws -> URL {
        let url = directory.appendingPathComponent(name)
        let image = try makeCGImage(width: 64, height: 48)
        guard
            let dest = CGImageDestinationCreateWithURL(
                url as CFURL, UTType.jpeg.identifier as CFString, 1, nil
            )
        else { throw FixtureError.cannotCreateDestination }

        var properties: [CFString: Any] = [:]
        if !exif.isEmpty { properties[kCGImagePropertyExifDictionary] = exif }
        if !tiff.isEmpty { properties[kCGImagePropertyTIFFDictionary] = tiff }
        if !gps.isEmpty { properties[kCGImagePropertyGPSDictionary] = gps }
        CGImageDestinationAddImage(dest, image, properties as CFDictionary)
        guard CGImageDestinationFinalize(dest) else { throw FixtureError.cannotWriteImage }
        return url
    }

    /// A diagonal red→blue ramp as a `CGImage`.
    ///
    /// The solid-colour `makeCGImage` above is fine for geometry and orientation, but useless for the
    /// render pipeline: a flat patch survives a tone curve almost unchanged, so a test built on one
    /// would pass against a stage that never ran.
    static func makeGradientCGImage(width: Int, height: Int) throws -> CGImage {
        let space = CGColorSpace(name: CGColorSpace.sRGB)!
        guard
            let ctx = CGContext(
                data: nil, width: width, height: height,
                bitsPerComponent: 8, bytesPerRow: width * 4, space: space,
                bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
            )
        else { throw FixtureError.cannotCreateContext }

        guard
            let gradient = CGGradient(
                colorsSpace: space,
                colors: [
                    CGColor(colorSpace: space, components: [0.9, 0.1, 0.1, 1])!,
                    CGColor(colorSpace: space, components: [0.1, 0.2, 0.9, 1])!,
                ] as CFArray,
                locations: [0, 1]
            )
        else { throw FixtureError.cannotCreateContext }

        ctx.drawLinearGradient(
            gradient,
            start: CGPoint(x: 0, y: 0),
            end: CGPoint(x: CGFloat(width), y: CGFloat(height)),
            options: [.drawsBeforeStartLocation, .drawsAfterEndLocation]
        )
        guard let image = ctx.makeImage() else { throw FixtureError.cannotCreateContext }
        return image
    }

    /// Write a gradient as **PNG** — lossless, so a test comparing a decode against a decode is
    /// measuring the pipeline rather than JPEG's ideas about chroma.
    @discardableResult
    static func writeGradientPNG(
        width: Int,
        height: Int,
        named name: String,
        in directory: URL
    ) throws -> URL {
        let url = directory.appendingPathComponent(name)
        let image = try makeGradientCGImage(width: width, height: height)
        guard
            let dest = CGImageDestinationCreateWithURL(
                url as CFURL, UTType.png.identifier as CFString, 1, nil
            )
        else { throw FixtureError.cannotCreateDestination }
        CGImageDestinationAddImage(dest, image, nil)
        guard CGImageDestinationFinalize(dest) else { throw FixtureError.cannotWriteImage }
        return url
    }

    /// Write a large grayscale ramp with fine alternating detail. This is intentionally unlike a
    /// flat or purely smooth fixture: both positive and negative Clarity must have visible local
    /// contrast to adjust while the broad ramp remains available for orientation checks.
    @discardableResult
    static func writeClarityPNG(
        width: Int,
        height: Int,
        named name: String,
        in directory: URL
    ) throws -> URL {
        let url = directory.appendingPathComponent(name)
        let colorSpace = CGColorSpace(name: CGColorSpace.sRGB)!
        var pixels = [UInt8](repeating: 0, count: width * height * 4)
        for y in 0..<height {
            for x in 0..<width {
                let ramp = 0.12 + 0.76 * CGFloat(y) / CGFloat(max(height - 1, 1))
                let detail = (x + y).isMultiple(of: 2) ? 0.08 : -0.08
                let value = UInt8(min(max((ramp + detail) * 255, 0), 255))
                let offset = (y * width + x) * 4
                pixels[offset] = value
                pixels[offset + 1] = value
                pixels[offset + 2] = value
                pixels[offset + 3] = 255
            }
        }
        let provider = CGDataProvider(data: Data(pixels) as CFData)!
        let image = CGImage(
            width: width,
            height: height,
            bitsPerComponent: 8,
            bitsPerPixel: 32,
            bytesPerRow: width * 4,
            space: colorSpace,
            bitmapInfo: CGBitmapInfo(rawValue: CGImageAlphaInfo.premultipliedLast.rawValue),
            provider: provider,
            decode: nil,
            shouldInterpolate: false,
            intent: .defaultIntent
        )!
        guard
            let dest = CGImageDestinationCreateWithURL(
                url as CFURL, UTType.png.identifier as CFString, 1, nil
            )
        else { throw FixtureError.cannotCreateDestination }
        CGImageDestinationAddImage(dest, image, nil)
        guard CGImageDestinationFinalize(dest) else { throw FixtureError.cannotWriteImage }
        return url
    }

    // MARK: - Local-only RAW

    /// A real RAW file, if a caller supplied a local fixture directory.
    ///
    /// Everything else here is generated, but a RAW cannot be: a synthetic DNG that `CIRAWFilter`
    /// will actually decode is a project of its own. Real-world fixtures are optional, so CI and
    /// checkouts without a licensed local fixture directory skip RAW-dependent tests rather than
    /// fail. See `realworldtest/README.md`.
    static var localRAWURLs: [URL] {
        let repoRoot = URL(fileURLWithPath: #filePath)  // Tests/LumoKitTests/Fixtures.swift
            .deletingLastPathComponent()  // Tests/LumoKitTests
            .deletingLastPathComponent()  // Tests
            .deletingLastPathComponent()  // repo root
        let folder =
            ProcessInfo.processInfo.environment["LUMO_RAW_FIXTURE_DIR"]
            .map { URL(fileURLWithPath: $0, isDirectory: true) }
            ?? repoRoot.appendingPathComponent("realworldtest", isDirectory: true)
        guard
            let entries = try? FileManager.default.contentsOfDirectory(
                at: folder, includingPropertiesForKeys: nil
            )
        else { return [] }
        return
            entries
            .filter { ImageDecoder.rawExtensions.contains($0.pathExtension.lowercased()) }
            .sorted { $0.lastPathComponent < $1.lastPathComponent }
    }

    static var localRAWURL: URL? {
        localRAWURLs.first
    }

    /// A real (RAW, in-camera JPG) pair, if the local fixture directory contains one.
    ///
    /// The derive gate needs both halves of the same frame: the cube is fit by comparing a neutral
    /// RAW render against the JPEG the camera produced from it. Matched on the filename stem, because
    /// that is how cameras write the pair and how a camera fixture directory holds one — anything
    /// looser could pick up an unrelated JPG and the geometry check would reject it with a confusing
    /// message.
    ///
    /// `nil` when `LUMO_RAW_FIXTURE_DIR` is not supplied. A test that needs this must `XCTSkip`.
    static var localRAWJPGPair: (raw: URL, jpg: URL)? {
        guard let raw = localRAWURL else { return nil }
        let stem = raw.deletingPathExtension().lastPathComponent
        let folder = raw.deletingLastPathComponent()
        guard
            let entries = try? FileManager.default.contentsOfDirectory(
                at: folder, includingPropertiesForKeys: nil
            )
        else { return nil }
        guard
            let jpg = entries.first(where: {
                ["jpg", "jpeg"].contains($0.pathExtension.lowercased())
                    && $0.deletingPathExtension().lastPathComponent == stem
            })
        else { return nil }
        return (raw, jpg)
    }

    /// Dimensions ImageIO reports for a file on disk.
    static func storedSize(of url: URL) -> CGSize? {
        guard let source = CGImageSourceCreateWithURL(url as CFURL, nil),
            let props = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
            let w = props[kCGImagePropertyPixelWidth] as? Int,
            let h = props[kCGImagePropertyPixelHeight] as? Int
        else { return nil }
        return CGSize(width: w, height: h)
    }

    enum FixtureError: Error {
        case cannotCreateContext
        case cannotCreateDestination
        case cannotWriteImage
    }
}

/// Base class that hands each test a scratch directory and cleans it up.
class TempDirectoryTestCase: XCTestCase {
    var tempDirectory: URL!
    private var testDefaultSuiteNames: [String] = []
    /// Every model created by a test is retained until teardown so its explicit async lifecycle
    /// barrier runs before the fixture directory is removed.
    private var appViewModels: [AppViewModel] = []

    /// Creates an AppViewModel whose persisted state is private to this test and whose managed
    /// library lives beside the test's generated fixtures. Tests that exercise relaunch behavior
    /// can pass the same `preferences` and `libraryFolderURL` to multiple calls.
    @MainActor
    func makeTestUserDefaults() -> UserDefaults {
        let suiteName = "LumoKitTests.AppViewModel-\(UUID().uuidString)"
        let defaults = UserDefaults(suiteName: suiteName)!
        defaults.removePersistentDomain(forName: suiteName)
        testDefaultSuiteNames.append(suiteName)
        return defaults
    }

    /// Creates a collection whose durable library and persisted state are private to this test.
    /// Collection tests must use this helper rather than the production defaults so generated
    /// imports can never land in the user's managed Library.
    @MainActor
    func makeTestCollection(
        scheduler: ImageWorkScheduler? = nil,
        defaults: UserDefaults? = nil,
        libraryFolderURL: URL? = nil
    ) -> ImageCollection {
        ImageCollection(
            scheduler: scheduler ?? ImageWorkScheduler(),
            defaults: defaults ?? makeTestUserDefaults(),
            libraryFolderURL: libraryFolderURL
                ?? tempDirectory.appendingPathComponent("managed-library", isDirectory: true)
        )
    }

    @MainActor
    func makeLUTLibrary(includeBundled: Bool = false) -> LUTLibrary {
        LUTLibrary(
            preferences: makeTestUserDefaults(),
            userLookFolderURL: tempDirectory.appendingPathComponent("looks", isDirectory: true),
            includeBundled: includeBundled
        )
    }

    @MainActor
    func makeAppViewModel(
        engine: any RenderEngining = FakeRenderEngine(),
        editStore: EditDocumentStore? = nil,
        preferences: UserDefaults? = nil,
        mediaVolumeProvider: any MediaVolumeProviding = MountedMediaVolumeProvider(),
        includeBundledLooks: Bool = false,
        libraryFolderURL: URL? = nil,
        userLookFolderURL: URL? = nil,
        photoAnalysisCoordinator: PhotoAnalysisCoordinator? = nil,
        embeddedFirstFrameProvider: @escaping @Sendable (URL) async -> NSImage? = { url in
            Thumbnails.generate(from: url, maxPixelSize: 1600)
        }
    ) -> AppViewModel {
        let isolatedPreferences: UserDefaults
        if let preferences {
            isolatedPreferences = preferences
        } else {
            isolatedPreferences = makeTestUserDefaults()
        }

        let viewModel = AppViewModel(
            engine: engine,
            editStore: editStore ?? makeInMemoryEditStore(),
            preferences: isolatedPreferences,
            mediaVolumeProvider: mediaVolumeProvider,
            includeBundledLooks: includeBundledLooks,
            libraryFolderURL: libraryFolderURL
                ?? tempDirectory.appendingPathComponent("managed-library", isDirectory: true),
            userLookFolderURL: userLookFolderURL
                ?? tempDirectory.appendingPathComponent("looks", isDirectory: true),
            photoAnalysisCoordinator: photoAnalysisCoordinator,
            embeddedFirstFrameProvider: embeddedFirstFrameProvider
        )
        appViewModels.append(viewModel)
        return viewModel
    }

    override func setUpWithError() throws {
        try super.setUpWithError()
        tempDirectory = try Fixtures.makeTempDirectory(String(describing: type(of: self)))
    }

    override func tearDown() async throws {
        for viewModel in appViewModels {
            await viewModel.shutdown()
        }
        appViewModels.removeAll()
        for suiteName in testDefaultSuiteNames {
            UserDefaults.standard.removePersistentDomain(forName: suiteName)
        }
        testDefaultSuiteNames.removeAll()
        if let tempDirectory {
            try? FileManager.default.removeItem(at: tempDirectory)
        }
        tempDirectory = nil
        try await super.tearDown()
    }
}
